### PR TITLE
smbus2 implementation of MLX90640 for non-CircuitPython use

### PR DESCRIPTION
**Pull request by jaysonlarose**
Hi, Adafruit!

I recently bought a couple of these thermal cameras, and wanted to get them running on embedded Linux boards (ie, Raspberry Pi, Beaglebone, et cetera).  I found your CircuitPython library most useful, and I figured I'd contribute the code back.

* Moved eeData into the main MLX90640 class.
  This is done because the data contained in each device's EEPROM is
  ostensibly unique to that device, and this prevents eeData being
  trampled if multiple devices are instantiated.
* Commented out unused _I2cReadWords call in MLX90640._I2CWriteWord.
  As the code that checks this data is commented out, it just seemed
  like additional traffic on the I2C bus without any benefit.
* Moved import of `adafruit_bus_device.i2c_device.I2CDevice` into
  `MLX90640.__init__()`.
  This allows the MLX90640 class to be superclassed (subclassed?
  I always get this verb wrong!) by smbus2_mlx90640.MLX90640.
* Created smbus2_mlx90640.py, which uses the smbus2 module for
  I2C communication (https://pypi.org/project/smbus2/)
* Quality of Life improvement to `MLX90640.getFrame()`:
  If the `framebuf` parameter is not supplied, one will be created.
  The contents of `framebuf` are also returned by this method.
  This allows you to call getFrame() without having to go through
  the extra step of creating a framebuf object.

Example code:

```
import smbus2, smbus2_mlx90640
bus = smbus2.SMBus(1)
m = smbus2_mlx90640.MLX90640(bus)
print(m.getFrame())
```

Disclaimer: I haven't tested these changes insofar as how they pertain to
CircuitPython, the Adafruit Bus Device Library, or the Adafruit Register
Library. The above example code, however, works just fine on a stock Raspberry
Pi 4 with nothing more than `pip3 install smbus2` having been run.
With `dtparam=i2c_arm=on,i2c_arm_baudrate=1000000` applied to /boot/config.txt,
I can set the refresh rate to REFRESH_32_HZ and push the raw data over an ssh
session at 16 frames per second.

### CODE REVIEW

**Comment by ladyada** [comment]
hiya thanks for the PR - we woudlnt' be able to merge the `smbus` addition - this driver works within CircuitPython's I2C wrapper (which communicates with the kernel smbus driver) and having an outside-of-circuitpython method is confusing to have here.

**Comment by jaysonlarose** [comment]
Fair enough — I figured I'd leave the code here in case it comes in useful for anybody.
I'm just glad to see the state of working with I2C in Python has improved since I last played around with it.
Thanks for figuring out and interpreting, well... all of the datasheets you've been through. I started trying to work through how to apply the calibration data for this breakout and my eyes just kind of glazed over!

**Comment by ladyada** [comment]
ok once its updated & passing CI let us know :)

**Comment by jaysonlarose** [comment]
It passes CI now!
I had to tell pylint to ignore the non-toplevel import statement — I had no idea that would be something picked up by a linter. Hopefully that's okay, I still use the smbus2 code and _my_ world breaks if it hits that import statement.

**Comment by ladyada** [comment]
@tannewt do we have a style policy on imports-not-at-top-level?

**Comment by tannewt** [comment]
Generally we should only use non-toplevel imports in the case that we want to save memory and only load a dependent library on use. Otherwise, it is just less clear.

In this case, I don't think we need the smbus change here. (Some of the other `self.` changes could be useful.)

@jaysonlarose Have you seen Blinka? It allows you to use CircuitPython libraries on single board computers: https://learn.adafruit.com/circuitpython-on-raspberrypi-linux It is pip installable so I'm not sure why a smbus2-only version is needed.

**Comment by jaysonlarose** [comment]
@tannewt What I've got is the Pimoroni versions of the MLX90640 breakout. I was already a fair amount into implementing the MLX90640 datasheet myself using the smbus2 module, until I hit the  part of the datasheet where they said that you need to pull calibration data out of EEPROM, and here are the mathematical formulas you need to use to apply them. My eyes started to glaze over and I started to lose my will to live just a tiny bit, and that's when I dug around and found the Adafruit CircuitPython libraries. At first, I'd just yanked out all of the `_Extract`* functions, but then I realized that the _only_ thing I needed to do to create a subclass of your module was override `__init__()`, `_I2CWriteWord()`, and `_I2CReadWords`, and what's more pythonic than that?

I didn't see that you had this Blinka compatibility shim until after I'd submitted the first revision of the pull request. I didn't _try_ it until just now. I'll be honest, I was really hoping to find something to justify the work I'd done, but after backporting the modified tool I wrote to pull video off the pi, I couldn't see any significant differences in performance between Blinka and smbus2. The _only_ things I've got are "It took one more pip statement to install", which is a lame excuse, and "my `_I2cReadWords()` implementation is simpler, potentially negligibly more performant, and potentially plays very slightly better on a busy multi-process i2c bus, because it doesn't need to split long reads into multiple transactions".

So I understand why it doesn't make sense to accept the smbus2 code, which is why I removed it from the pull request. I'd really like it if you allowed the non-toplevel import into your codebase, for one important reason that you didn't mention: It means I can subclass your library and continue to use it with my smbus2 implementation.

There's a bit of irony here; I want to continue using smbus2 for the exact same reason you don't want the smbus2 bits.... Blinka is confusing! The src directory is 1.3 megabytes in size, and that's not even dealing with the busdevice,  platformdetect, or pureio packages! It's got binary executables kicking around in there! In the "src" directory! I can look at smbus2 and grok it within 5 minutes. I know it's running close to the metal in that when you open the hood and look inside, it's mostly syscalls. I'd compare it to the hacky ctypes implementation I made back in 2017 because I couldn't find any python i2c library that could do a repeated start bit, but that'd be giving what I wrote too much credit. I used a raspberry pi 4 with 8 gigabytes of ram when I compared the performance of Blinka vs smbus2, but I have no idea how they'd compare if I tried it on one of my anemic old beaglebones instead. With an interpreted language, I can't imagine it'd be flattering.

As an aside, I saw on your product page for the breakout (<https://www.adafruit.com/product/4407>) I saw that you said "With a maximum frame rate of 16 Hz (the theoretical limit is 32Hz but we were not able to practically achieve it)".  I know the datasheet has an option for setting the refresh rate up to 64Hz, but I have a certain amount of doubt that it's even theoretically possible. I added in some rudimentary profiling in my own attempts to make it go fast, and when running under `REFRESH_32_HZ` with the I2C bus set to 1MHz, my pi 4 is spending 60.24% of it's wallclock time performing `i2c_rdwr` syscalls, 47.27% of which are specifically the syscall that retrieves field data from the module (in other words, peeking and poking the status register is omitted), and it pokes the status register on average 39.64 times before a new field is made available. If I modify the code to add a `sleep(0.001)` in between each time it checks the status register, these statistics drop down to 49.69% for all i2c calls, 47.28% retrieving field data, and 3.18 pokes per field. In other words, those tolerances are so tight I think you'd just have to ignore the status register and somehow pull field data in lockstep in order to reach that maximum speed.

You can, however, get smoother, more temporally accurate video by "cheating". Notice above I've been talking about "fields", not "frames".  I'm using that term like if we were talking about analog broadcast television... except our fields happen to look like a chessboard.  One of the first modifications I made to your library was to make a `getField()` function, so I could persist the frame buffer, composite each new field onto it, and send that out as a video frame. Here's a nice little video I made of using that method to pull video off of my pi at a silky smooth 32 FPS: <https://www.interlaced.org/mlx90640.mkv>  (Here's a YouTube video for when I eventually remove the first video from my server, but their recompression looks terrible: <https://www.youtube.com/shorts/1ijalnqL-UA>). I pull the video frames off the pi using an ssh session, and feed it into a v4l2loopback device using ffmpeg, so I can record it, use it as a webcam, import it into OBS as a video source....

**Comment by ladyada** [comment]
sounds good! 

yep blinka is pretty large, even though technically there isnt that much code in it, because we try to support a vast number of single board linux computers (each with different ways of accessing GPIO), and usb to gpio expanders on cpython.  we specifically didn't want to use smbus in blinka - we instead perform the ioctl direct to kernel with PureIO https://github.com/adafruit/Adafruit_Python_PureIO - there are some linux platforms we support that are so minimal they could not install/compile extensions. there were some other constraints or bugs but we can't remember what those were, could be they were resolved :)

you're free to take this code and adapt it however you wish,  a fork may be the best way to maintain your variant. if you have PR updates to this library feel free to submit them :) thanks!

**Pull request closed without merging**
