### PR TITLE
Add Missing Type Annotations

### LINKED ISSUE #26: Missing Type Annotations
There are missing type annotations for some functions in this library.

The `typing` module does not exist on CircuitPython devices so the import needs to be wrapped in try/except to catch the error for missing import. There is an example of how that is done here:

```python
try:
    from typing import List, Tuple
except ImportError:
    pass
```

Once imported the typing annotations for the argument type(s), and return type(s) can be added to the function signature. Here is an example of a function that has had this done already:

```python
def wrap_text_to_pixels(
    string: str, max_width: int, font=None, indent0: str = "", indent1: str = ""
) -> List[str]:
```
If you are new to Git or Github we have a guide about contributing to our projects here: https://learn.adafruit.com/contribute-to-circuitpython-with-git-and-github

There is also a guide that covers our CI utilities and how to run them locally to ensure they will pass in Github Actions here: https://learn.adafruit.com/creating-and-sharing-a-circuitpython-library/check-your-code In particular the pages: `Sharing docs on ReadTheDocs` and `Check your code with pre-commit` contain the tools to install and commands to run locally to run the checks.

If you are attempting to resolve this issue and need help, you can post a comment on this issue and tag both @foamyguy and @kattni or reach out to us on Discord: https://adafru.it/discord in the `#circuitpython-dev` channel.

The following locations are reported by mypy to be missing type annotations:

- [ ] adafruit_mlx90640.py:87
- [ ] adafruit_mlx90640.py:110
- [ ] adafruit_mlx90640.py:117
- [ ] adafruit_mlx90640.py:133
- [ ] adafruit_mlx90640.py:162
- [ ] adafruit_mlx90640.py:178
- [ ] adafruit_mlx90640.py:191
- [ ] adafruit_mlx90640.py:771
- [ ] adafruit_mlx90640.py:777
- [ ] adafruit_mlx90640.py:790
- [ ] adafruit_mlx90640.py:796
- [ ] adafruit_mlx90640.py:813

### PR DESCRIPTION
**Pull request by tcfranks**
resolves #26 
submitted for review / comment

### CODE REVIEW

**Comment by tcfranks** [comment]
submitted for review / comment

PS> I think the yield in line 779 should return an Iterator[Tuple[int, int]] but that is breaking the precommits, so maybe not...

**Comment by tcfranks** [comment]
@tekktrik , @FoamyGuy ,
Did I gum this one up somehow with my comment, is it waiting on me, or is it just down in the queue?  I slowed down after hactoberfest to let the smoke clear, but I have 3 or 4 more other pr's to submit, but wanted to get this out of the way first.....

Thanks!

**Comment by tekktrik** [comment]
Looks like this just fell through the cracks.  I'll request a review and try to get to it shortly if no one else does first.

**Review by FoamyGuy — APPROVED** [review]
Looks good to me, thanks @tcfranks!

I don't have the hardware for testing, but don't spot anything during review that would change behavior.

Nothing you did caused the delay, this one just fell through the cracks and tekktrik and I have been getting into some other things lately. 

I'm still in the process of making a sweep through open PRs today (with an intermission for the meeting). If you've got others that are waiting on us feel free to ping me on them and I'll bump them up my list for this afternoon.

**Pull request merged**
