### PR TITLE
Update mlx90640_pygamer.py

### PR DESCRIPTION
**Pull request by dglaude**
Use simpleio.map_range, remove custom function, more comments, cleaning, rename to max_t and min_t, general improvement.

No new functionality, just possibly easier to understand code and removing a custom function doing map_range.

### CODE REVIEW

**Comment by dglaude** [comment]
This should fix #6

**Comment by caternuson** [comment]
Looks good. Did you also test just to make sure it all still runs as expected?

**Comment by dglaude** [comment]
Yes, I have recovered my hardware and it was tested.

Actually, I never tested on Adafruit Stemma/breakout but only on my older Pimoroni Breakout Garden version. This is why I would love to see someone plugging a Stemma cable  between a PyGamer and the Adafruit mlx90640 breakout board. (please take a picture).

I also have a PyPortal, so I may do a version with that resolution (but first I need to find/build a Stemma to Pimoroni Breakout Garden cable).

**Comment by caternuson** [comment]
OK. Those are just different ways of making the I2C connection. So shouldn't really matter in terms of testing the code. As long as you had some hardware setup for testing, should be fine.

**Review by caternuson — APPROVED** [review]

**Pull request merged**
